name: Build and Deploy Payment Service

on:
  push:
    branches:
      - "main"
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./payment-service/gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
          build-root-directory: payment-service
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./payment-service
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/payment-service:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Docker
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.AWS_HOST4 }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_KEY }}
          port: ${{ secrets.AWS_PORT }}
          script: |
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/payment-service:latest
            sudo docker stop payment-service
            sudo docker rm payment-service
            sudo docker run -d -p 8083:8083 --name payment-service -e SPRING.DATASOURCE.URL=jdbc:mysql://${{ secret.MYSQL_URL }}/${{ secret.MYSQL_DB }}?createDatabaseIfNotExist=true -e SPRING.DATASOURCE.USERNAME=${{ secret.MYSQL_USER }} -e SPRING.DATASOURCE.PASSWORD=${{ secret.MYSQL_PASSWORD }} -e secretKeyAws=${{ secret.SECRETKEYAWS }} -e accessKeyAws=${{ secret.ACCESSKEYAWS }} -e bucketAws=${{ secret.BUCKETAWS }} -e regionAws=${{ secret.REGIONAWS }} -e keyJWT=${{ secret.KEYJWT }} ${{ secrets.DOCKERHUB_USERNAME }}/payment-service:latest
