name: Build and Deploy Reservation Service

on:
  push:
    branches:
      - "main"
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
          
      - name: Grant execute permission for gradlew
        run: chmod +x ./reservation-service/gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: bootJar
          build-root-directory: reservation-service
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./reservation-service
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/reservation-service:latest 

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Docker
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.AWS_HOST3 }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_KEY }}
          port: ${{ secrets.AWS_PORT }}
          script: |
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/reservation-service:latest
            sudo docker stop reservation-service
            sudo docker rm reservation-service
            sudo docker run -d -p 8082:8082 --name reservation-service -e SPRING.DATASOURCE.URL=jdbc:mysql://${{ secrets.MYSQL_URL }}/${{ secrets.MYSQL_DB }}?createDatabaseIfNotExist=true -e SPRING.DATASOURCE.USERNAME=${{ secrets.MYSQL_USER }} -e SPRING.DATASOURCE.PASSWORD=${{ secrets.MYSQL_PASSWORD }} -e secretKeyAws=${{ secrets.SECRETKEYAWS }} -e accessKeyAws=${{ secrets.ACCESSKEYAWS }} -e bucketAws=${{ secrets.BUCKETAWS }} -e regionAws=${{ secrets.REGIONAWS }} -e keyJWT=${{ secrets.KEYJWT }} ${{ secrets.DOCKERHUB_USERNAME }}/reservation-service:latest
